AWSTemplateFormatVersion: '2010-09-09'
Description: A static website - only works in us-east-1
Parameters:
  DomainName:
    Description: Alias for the CloudFront Distribution
    Type: String
  HostedZoneId:
    Description: Hosted zone that the DomainName can be created in.
    Type: AWS::Route53::HostedZone::Id
Resources:
  Bucket:
    Type: AWS::S3::Bucket
  OriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub "Sample::Generic::StaticWebsite in ${AWS::StackName}"
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref 'Bucket'
      PolicyDocument:
        Version: '2012-10-17'
        Id: OAIPolicy
        Statement:
          - Sid: OAIStatement
            Principal:
              CanonicalUser: !GetAtt 'OriginAccessIdentity.S3CanonicalUserId'
            Effect: Allow
            Action: s3:GetObject
            Resource: !Sub 'arn:aws:s3:::${Bucket}/*'
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      LifecycleConfiguration:
        Rules:
          - Id: ExpireOldLogs
            ExpirationInDays: 35
            Status: Enabled
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref 'DomainName'
      DomainValidationOptions:
        - DomainName: !Ref 'DomainName'
          HostedZoneId: !Ref 'HostedZoneId'
      ValidationMethod: DNS
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref 'DomainName'
        CacheBehaviors: []
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          ForwardedValues:
            QueryString: false
          Compress: true
          DefaultTTL: 10
          TargetOriginId: s3
          ViewerProtocolPolicy: redirect-to-https
        DefaultRootObject: index.html
        Enabled: true
        HttpVersion: http2
        IPV6Enabled: true
        Logging:
          Bucket: !Sub '${LogBucket}.s3.amazonaws.com'
        Origins:
          - Id: s3
            DomainName: !Sub '${Bucket}.s3.amazonaws.com'
            S3OriginConfig:
              OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessIdentity}'
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn: !Ref 'Certificate'
          SslSupportMethod: sni-only
  RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref 'HostedZoneId'
      RecordSets:
        - Type: A
          Name: !Ref 'DomainName'
          AliasTarget:
            DNSName: !GetAtt 'Distribution.DomainName'
            EvaluateTargetHealth: true
            HostedZoneId: Z2FDTNDATAQYW2
        - Type: AAAA
          Name: !Ref 'DomainName'
          AliasTarget:
            DNSName: !GetAtt 'Distribution.DomainName'
            EvaluateTargetHealth: true
            HostedZoneId: Z2FDTNDATAQYW2
